# Generated by Django 5.1.2 on 2024-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("book_name", models.CharField(max_length=100)),
                ("is_checked_out", models.BooleanField(default=False)),
            ],
        ),
    ]
